/*
* generated by Xtext
*/
package at.fhj.gaar.androidapp;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AppDslStandaloneSetup extends AppDslStandaloneSetupGenerated{

	public static void doSetup() {
		new AppDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

