/*
 * generated by Xtext
 */
package at.fhj.gaar.androidapp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AppDslRuntimeModule extends at.fhj.gaar.androidapp.AbstractAppDslRuntimeModule {

}
