/*
* generated by Xtext
*/
package at.fhj.gaar.androidapp.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.fhj.gaar.androidapp.services.AppDslGrammarAccess;

public class AppDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AppDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.fhj.gaar.androidapp.parser.antlr.internal.InternalAppDslParser createParser(XtextTokenStream stream) {
		return new at.fhj.gaar.androidapp.parser.antlr.internal.InternalAppDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AndroidAppProject";
	}
	
	public AppDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AppDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
