/**
 * generated by Xtext
 */
package at.fhj.gaar.androidapp.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class AppDslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
