/*
 * generated by Xtext
 */
package at.fhj.gaar.androidapp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AppDslUiModule extends at.fhj.gaar.androidapp.ui.AbstractAppDslUiModule {
	public AppDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
