/**
 * generated by Xtext
 */
package at.fhj.gaar.androidapp.ui.contentassist;

import at.fhj.gaar.androidapp.ui.contentassist.AbstractAppDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AppDslProposalProvider extends AbstractAppDslProposalProvider {
}
