/*
 * generated by Xtext
 */
package at.fhj.gaar.androidapp.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAppDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(at.fhj.gaar.androidapp.appDsl.AppDslPackage.eINSTANCE);
		return result;
	}
}
