/**
 * generated by Xtext
 */
package at.fhj.gaar.androidapp.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class AppDslQuickfixProvider extends DefaultQuickfixProvider {
}
