/*
* generated by Xtext
*/
package at.fhj.gaar.androidapp;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AppDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.fhj.gaar.androidapp.ui.internal.AppDslActivator.getInstance().getInjector("at.fhj.gaar.androidapp.AppDsl");
	}
	
}
